extraction:
  csharp:
    index:
      solution: "Cli/Cli.csproj"
      dotnet:
        arguments: "-c release"
        version: "3.1.201"

extraction:
  csharp:
    index:
      solution: "Tests/Tests.csproj"
      dotnet:
        arguments: "-c release"
        version: "3.1.201"

extraction:
  csharp:
    index:
      solution: "Benchmarks/Benchmarks.csproj"
      dotnet:
        arguments: "-c release"
        version: "3.1.201"

extraction:
  csharp:
    index:
      solution: "Lib/Lib.csproj"
      dotnet:
        arguments: "-c release"
        version: "3.1.201"