//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttackSurfaceAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttackSurfaceAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectors.
        /// </summary>
        internal static string Collectors {
            get {
                return ResourceManager.GetString("Collectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing.
        /// </summary>
        internal static string Comparing {
            get {
                return ResourceManager.GetString("Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted database..
        /// </summary>
        internal static string DeletedDatabase {
            get {
                return ResourceManager.GetString("DeletedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done writing!.
        /// </summary>
        internal static string DoneWriting {
            get {
                return ResourceManager.GetString("DoneWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due to filter.
        /// </summary>
        internal static string DueToFilter {
            get {
                return ResourceManager.GetString("DueToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating Collect Run Ids.
        /// </summary>
        internal static string EnumeratingCollectRunIds {
            get {
                return ResourceManager.GetString("EnumeratingCollectRunIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating Monitor Run Ids.
        /// </summary>
        internal static string EnumeratingMonitorRunIds {
            get {
                return ResourceManager.GetString("EnumeratingMonitorRunIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get access control for.
        /// </summary>
        internal static string Err_AccessControl {
            get {
                return ResourceManager.GetString("Err_AccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error collecting from.
        /// </summary>
        internal static string Err_CollectingFrom {
            get {
                return ResourceManager.GetString("Err_CollectingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when comparing.
        /// </summary>
        internal static string Err_Comparing {
            get {
                return ResourceManager.GetString("Err_Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine latest run id. Can&apos;t continue..
        /// </summary>
        internal static string Err_CouldntDetermineOneRun {
            get {
                return ResourceManager.GetString("Err_CouldntDetermineOneRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine latest two run ids. Can&apos;t continue..
        /// </summary>
        internal static string Err_CouldntDetermineTwoRun {
            get {
                return ResourceManager.GetString("Err_CouldntDetermineTwoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception checking for file signature for.
        /// </summary>
        internal static string Err_ExceptionCheckSig {
            get {
                return ResourceManager.GetString("Err_ExceptionCheckSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something appears to be wrong with your filters file.
        /// </summary>
        internal static string Err_FiltersFile {
            get {
                return ResourceManager.GetString("Err_FiltersFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No collectors have been defined.
        /// </summary>
        internal static string Err_NoCollectors {
            get {
                return ResourceManager.GetString("Err_NoCollectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No monitors have been defined..
        /// </summary>
        internal static string Err_NoMonitors {
            get {
                return ResourceManager.GetString("Err_NoMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Surface Enumerator must be run as Administrator..
        /// </summary>
        internal static string Err_RunAsAdmin {
            get {
                return ResourceManager.GetString("Err_RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Surface Enumerator must be run as root..
        /// </summary>
        internal static string Err_RunAsRoot {
            get {
                return ResourceManager.GetString("Err_RunAsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That runid was already used. Must use a unique runid for each run. Use --overwrite to discard previous run information..
        /// </summary>
        internal static string Err_RunIdAlreadyUsed {
            get {
                return ResourceManager.GetString("Err_RunIdAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceCollector cannot run on this platform..
        /// </summary>
        internal static string Err_ServiceCollectorIncompat {
            get {
                return ResourceManager.GetString("Err_ServiceCollectorIncompat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping.
        /// </summary>
        internal static string Err_Stopping {
            get {
                return ResourceManager.GetString("Err_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to take hash of file.
        /// </summary>
        internal static string Err_UnableToHash {
            get {
                return ResourceManager.GetString("Err_UnableToHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluding hive.
        /// </summary>
        internal static string ExcludingHive {
            get {
                return ResourceManager.GetString("ExcludingHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed parsing (no entry?).
        /// </summary>
        internal static string FailedParsed {
            get {
                return ResourceManager.GetString("FailedParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating file hash for.
        /// </summary>
        internal static string FileHash {
            get {
                return ResourceManager.GetString("FileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting result types.
        /// </summary>
        internal static string GettingResultTypes {
            get {
                return ResourceManager.GetString("GettingResultTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path supplied was invalid..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded filters from.
        /// </summary>
        internal static string LoadedFilters {
            get {
                return ResourceManager.GetString("LoadedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring, press CTRL+C to stop....
        /// </summary>
        internal static string MonitoringPressC {
            get {
                return ResourceManager.GetString("MonitoringPressC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor started for.
        /// </summary>
        internal static string MonitorStartedFor {
            get {
                return ResourceManager.GetString("MonitorStartedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully parsed.
        /// </summary>
        internal static string SuccessParsed {
            get {
                return ResourceManager.GetString("SuccessParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your telemetry opt out setting is now.
        /// </summary>
        internal static string TelemetryOptOut {
            get {
                return ResourceManager.GetString("TelemetryOptOut", resourceCulture);
            }
        }
    }
}
