parameters:
# Job Name
- name: jobName
  type: string
  default: 'publish_win'
# Optional Pre-Build Steps
- name: 'preBuild'
  type: stepList
  default: []
# Version of Dotnet SDK to use
- name: dotnetVersion
  type: string
  default: '5.x'
# Version of NuGet Tool to use
- name: nugetVersion
  type: string
  default: '5.x'
# Path to .csproj or .sln
- name: projectPath
  type: string
  default: ''
# Build Configuration
- name: buildConfiguration
  type: string
  default: 'Release'
# Project Name
- name: projectName
  type: string
  default: ''
# Release Version
- name: releaseVersion
  type: string
  default: ''
# Pipeline Artifact Name
- name: artifactName
  type: string
  default: 'Unsigned_Binaries'

jobs:
- job: ${{ parameters.jobName }}
  displayName: Dotnet Publish Win/NetCoreApp
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NuGetAuthenticate@1  
  - task: UseDotNet@2
    displayName: Install Dotnet SDK
    inputs:
      packageType: 'sdk'
      version: ${{ parameters.dotnetVersion }}
  - task: NuGetToolInstaller@1
    displayName: Install Nuget Tool
    inputs:
      versionSpec: ${{ parameters.nugetVersion }}
  - ${{ parameters.preBuild }}
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      feedsToUse: config
      nugetConfigPath: NuGet.Config.AzureArtifacts
      projects: ${{ parameters.projectPath }}
      verbosityRestore: 'Normal'
  - task: DotNetCoreCLI@2
    displayName: Publish Win x64
    inputs:
      command: 'publish'
      arguments: '${{ parameters.projectPath }} -c ${{ parameters.buildConfiguration }} -o bin/win/${{ parameters.projectName }}_win_$(ReleaseVersion) -r win-x64'
      publishWebProjects: false
      zipAfterPublish: false
  - task: DotNetCoreCLI@2
    displayName: Build .NET Core App
    inputs:
      command: 'publish'
      arguments: '${{ parameters.projectPath }} -c ${{ parameters.buildConfiguration }} -o bin/netcoreapp/${{ parameters.projectName }}_netcoreapp_$(ReleaseVersion)'
      publishWebProjects: false
      zipAfterPublish: false
  - task: AntiMalware@3
    displayName: Anti-Malware Scan
    inputs:
      InputType: 'Basic'
      ScanType: 'CustomScan'
      FileDirPath: 'bin'
      EnableServices: true
      SupportLogOnError: true
      TreatSignatureUpdateFailureAs: 'Warning'
      SignatureFreshness: 'UpToDate'
      TreatStaleSignatureAs: 'Warning'
  - task: ArchiveFiles@2
    displayName: Archive Builds
    inputs:
      rootFolderOrFile: 'bin'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'Archives\${{ parameters.projectName }}_Win_NetCoreApp.zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    displayName: Pipeline Publish Archive
    inputs:
      PathtoPublish: 'Archives'
      ArtifactName: '${{ parameters.artifactName }}'
      publishLocation: 'Container'