parameters:
# Job Name
- name: jobName
  type: string
  default: 'dotnet_test'
# Version of Dotnet SDK to use
- name: dotnetVersion
  type: string
  default: '7.0.x'
# Version of Dotnet SDK to use
- name: dotnetVersionLTS
  type: string
  default: '6.0.x'
# Version of NuGet Tool to use
- name: nugetVersion
  type: string
  default: '5.x'
# List of paths to .csproj
- name: projectPath
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: Dotnet Test
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: Install Dotnet SDK
    inputs:
      packageType: 'sdk'
      version: ${{ parameters.dotnetVersion }}
  - task: UseDotNet@2
    displayName: Install Dotnet SDK
    inputs:
      packageType: 'sdk'
      version: ${{ parameters.dotnetVersionLTS }}
  - task: DotNetCoreCLI@2
    displayName: Dotnet Test
    inputs:
      command: 'test'
      projects: ${{ parameters.projectPath }}