# Azure Pipelines
# https://aka.ms/yaml

name: ASA_Release_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
  # batch: true
  # branches:
  #   include:
  #   - release/v2.3
  # paths:
  #   include:
  #   - Cli
  #   - Lib
  #   - Pipelines
  #   - analyses.json
#pr: none
pr: none

resources:
  repositories:
    - repository: templates
      type: git
      name: SecurityEngineering/OSS-Tools-Pipeline-Templates
      ref: refs/tags/v2.0.0
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  BuildConfiguration: 'Release'
  DotnetVersion: '8.0.x'
  DotnetTargetFramework: 'net8.0'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    stages:
    - stage: Test
      dependsOn: []
      jobs:
      - template: dotnet-test-job.yml@templates
        parameters:
          jobName: 'dotnet_test_windows'
          dotnetVersions: ['6.0.x','7.0.x','8.0.x']
          poolName: MSSecurity-1ES-Build-Agents-Pool
          poolImage: MSSecurity-1ES-Windows-2022
          poolOs: windows
          projectPath: 'Tests/Tests.csproj'

    - stage: Build
      dependsOn: Test
      jobs:
      - template: dotnet-publish-linux-mac-job.yml@templates
        parameters:
          buildConfiguration: '${{ variables.BuildConfiguration }}'
          dotnetVersion: '${{ variables.DotnetVersion }}'
          targetFramework: '${{ variables.DotnetTargetFramework }}'
          projectPath: 'Cli/Cli.csproj'
          projectName: 'ASA'
          exePath: 'Asa'
          artifactName: 'linux-mac-archive'
          preBuild:
          - template: nbgv-set-version-steps.yml@templates
      - template: dotnet-publish-win-netcore-job.yml@templates
        parameters:
          buildConfiguration: '${{ variables.BuildConfiguration }}'
          dotnetVersion: '${{ variables.DotnetVersion }}'
          targetFramework: '${{ variables.DotnetTargetFramework }}'
          projectPath: 'Cli/Cli.csproj'
          projectName: 'ASA'
          artifactName: 'cli-archive'
          preBuild:
          - template: nbgv-set-version-steps.yml@templates
      - template: nuget-build-job.yml@templates
        parameters:
          jobName: 'pack_lib'
          buildConfiguration: '${{ variables.BuildConfiguration }}'
          dotnetVersion: '${{ variables.DotnetVersion }}'
          projectPath: 'Lib/Lib.csproj'
          projectName: 'ASA_Lib'
          artifactName: 'nuget-lib-archive'
          preBuild:
          - template: nbgv-set-version-steps.yml@templates
      - template: nuget-build-job.yml@templates
        parameters:
          jobName: 'pack_cli'
          buildConfiguration: '${{ variables.BuildConfiguration }}'
          dotnetVersion: '${{ variables.DotnetVersion }}'
          projectPath: 'Cli/Cli.csproj'
          projectName: 'ASA_Cli'
          artifactName: 'nuget-cli-archive'
          preBuild:
          - template: nbgv-set-version-steps.yml@templates
