name: ASA Release

trigger:
  batch: true
  paths:
    include:
    - Cli
    - Lib
  branches:
    include:
    - release/v2.*
    exclude:
    - release/v2.0

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Test
  jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'

    steps:
    - script: 'dotnet tool install -g nbgv'
      displayName: 'Install GitVersioning'
      
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build Tests'
      inputs:
        projects: 'Tests/Tests.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.binariesdirectory)\Tests'

    - task: VSTest@2
      displayName: 'Run Tests'
      inputs:
        testAssemblyVer2: AsaTests.dll
        searchFolder: '$(build.binariesdirectory)\Tests'

- stage: Build
  jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - script: 'dotnet tool install -g nbgv'
      displayName: 'Install GitVersioning'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publish ASA Windows'
      inputs:
        command: publish
        projects: 'Cli/Cli.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.binariesdirectory)\windows\ -r win-x64'
        zipAfterPublish: false

    - task: AntiMalware@3
      inputs:
        InputType: 'Basic'
        ScanType: 'CustomScan'
        FileDirPath: '$(Build.binariesdirectory)'
        EnableServices: true
        SupportLogOnError: false
        TreatSignatureUpdateFailureAs: 'Warning'
        SignatureFreshness: 'UpToDate'
        TreatStaleSignatureAs: 'Warning'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Interim Build Artifacts'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)\windows'
        ArtifactName: 'WindowsBuild'

    # Signing task requires .NET Core 2.X
    - task: UseDotNet@2
      inputs:
        packageType: 'runtime'
        version: '2.2.x'

    - task: EsrpCodeSigning@1
      inputs:
        ConnectedServiceName: 'CodeSignforATSAN'
        FolderPath: '$(build.binariesdirectory)/windows'
        Pattern: 'Asa.exe, Asa.dll, AsaLib.dll'
        signConfigType: 'inlineSignParams'
        inlineOperation: |
          [
              {
              "keyCode": "CP-230012",
              "operationSetCode": "SigntoolSign",
              "parameters": [
                  {
                  "parameterName": "OpusName",
                  "parameterValue": "Microsoft"
                  },
                  {
                  "parameterName": "OpusInfo",
                  "parameterValue": "http://www.microsoft.com"
                  },
                  {
                  "parameterName": "PageHash",
                  "parameterValue": "/NPH"
                  },
                  {
                  "parameterName": "FileDigest",
                  "parameterValue": "/fd sha256"
                  },
                  {
                  "parameterName": "TimeStamp",
                  "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                  }
              ],
              "toolName": "signtool.exe",
              "toolVersion": "6.2.9304.0"
              }
          ]
        SessionTimeout: '60'
        MaxConcurrency: '50'
        MaxRetryAttempts: '5'

    - task: PowerShell@2
      displayName: Compile CodeSign Summaries for Publication
      inputs:
        targetType: 'inline'
        script: |
          mkdir $(build.binariesdirectory)\CodeSign
          Get-ChildItem -Path $(build.binariesdirectory) -Recurse -Filter CodeSign* | foreach { Copy-Item -Path $_.FullName -Destination $(build.binariesdirectory)\CodeSign\$_.Name }

    - task: PublishBuildArtifacts@1
      displayName: 'Publish CodeSign Summaries'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)\CodeSign'
        ArtifactName: 'CodeSign'

    - task: PowerShell@2
      displayName: Prepare Artifacts
      inputs:
        targetType: 'inline'
        script: |
          $longVersion = (nbgv get-version -v AssemblyInformationalVersion)
          $version = $longVersion.split('+')[0]
          $asaFolder = "$(build.binariesdirectory)\Asa-win-$version"
          mkdir $asaFolder

          Move-Item -Path "$(build.binariesdirectory)\windows" -Destination $asaFolder

          7z a "$(build.artifactstagingdirectory)\Asa-win-$version.zip" $asaFolder

          Get-ChildItem $(build.artifactstagingdirectory) | Foreach-Object{
            $name = $_.Name
            $tmp = (Get-FileHash "$(build.artifactstagingdirectory)\$name").Hash
            Add-Content $(build.binariesdirectory)\HASHES_WINDOWS.txt "$tmp`t$name"
          }

    - task: PublishBuildArtifacts@1
      displayName: 'Publish HASHES.txt'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)\HASHES_WINDOWS.txt'
        ArtifactName: 'HASHES'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'BINARIES'

    - task: GitHubRelease@1
      displayName: 'GitHub release update'
      inputs:
        gitHubConnection: 'Gabe-Asa'
        action: edit
        tag: 'v$(Build.BuildNumber)'
        title: 'v$(Build.BuildNumber)'
        assets: '$(build.artifactstagingdirectory)/*'
        assetUploadMode: replace
        isDraft: false
        isPreRelease: false
        changeLogCompareToRelease: lastNonDraftRelease

  - job: Linux
    pool:
        vmImage: 'ubuntu-latest'
    steps:
    - script: 'dotnet tool install -g nbgv'
      displayName: 'Install GitVersioning'
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    - task: DotNetCoreCLI@2
      displayName: 'Publish ASA Linux'
      inputs:
          command: publish
          projects: 'Cli/Cli.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(build.binariesdirectory)/linux -r linux-x64'
          zipAfterPublish: false

    - task: CmdLine@2
      inputs:
        script: |
          VERSION="$(nbgv get-version -v AssemblyInformationalVersion | cut -d'+' -f 1)"

          mv $BIN_DIR/linux $BIN_DIR/Asa-linux-$VERSION
          
          tar -czvf $ART_DIR/Asa-linux-$VERSION.tar.gz $BIN_DIR/Asa-linux-$VERSION

          sha256sum $ART_DIR/Asa-linux-$VERSION.tar.gz | awk ' { n=split($2, a, "/"); $2 = a[n]; print; } ' OFS='\t' >> $BIN_DIR/HASHES_LINUX.txt
      displayName: 'Prepare Artifacts'
      env:
        BIN_DIR: $(build.binariesdirectory)
        ART_DIR: $(build.artifactstagingdirectory)
        SRC_DIR: $(build.sourcesdirectory)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish HASHES'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)/HASHES_LINUX.txt'
        ArtifactName: 'HASHES'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/'
        ArtifactName: 'BINARIES'

    - task: GitHubRelease@1
      displayName: 'GitHub release update'
      inputs:
        gitHubConnection: 'Gabe-Asa'
        action: edit
        tag: 'v$(Build.BuildNumber)'
        title: 'v$(Build.BuildNumber)'
        assets: '$(build.artifactstagingdirectory)/*'
        assetUploadMode: replace
        isDraft: false
        isPreRelease: false
        changeLogCompareToRelease: lastNonDraftRelease

  - job: Mac
    pool:
        vmImage: 'macOS-latest'
    steps:
    - script: 'dotnet tool install -g nbgv'
      displayName: 'Install GitVersioning'
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: DotNetCoreCLI@2
      displayName: 'Publish ASA macOS'
      inputs:
          command: publish
          projects: 'Cli/Cli.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(build.binariesdirectory)/macos -r osx-x64'
          zipAfterPublish: false

    - task: CmdLine@2
      inputs:
        script: |
          VERSION="$(nbgv get-version -v AssemblyInformationalVersion | cut -d'+' -f 1)"

          mv $BIN_DIR/macos $BIN_DIR/Asa-macos-$VERSION
          
          tar -czvf $ART_DIR/Asa-macos-$VERSION.tar.gz $BIN_DIR/Asa-macos-$VERSION

          sha256sum $ART_DIR/Asa-macos-$VERSION.tar.gz | awk ' { n=split($2, a, "/"); $2 = a[n]; print; } ' OFS='\t' >> $BIN_DIR/HASHES_MAC.txt
      displayName: 'Prepare Artifacts'
      env:
        BIN_DIR: $(build.binariesdirectory)
        ART_DIR: $(build.artifactstagingdirectory)
        SRC_DIR: $(build.sourcesdirectory)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish HASHES'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)/HASHES_MAC.txt'
        ArtifactName: 'HASHES'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifaces'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/'
        ArtifactName: 'BINARIES'

    - task: GitHubRelease@1
      displayName: 'GitHub release update'
      inputs:
        gitHubConnection: 'Gabe-Asa'
        action: edit
        tag: 'v$(Build.BuildNumber)'
        title: 'v$(Build.BuildNumber)'
        assets: '$(build.artifactstagingdirectory)/*'
        assetUploadMode: replace
        isDraft: false
        isPreRelease: false
        changeLogCompareToRelease: lastNonDraftRelease

  - job: Nuget
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - script: 'dotnet tool install -g nbgv'
      displayName: 'Install GitVersioning'

    - task: DotNetCoreCLI@2
      displayName: Nupkg (Lib)
      inputs:
        command: 'custom'
        custom: 'pack'
        arguments: 'Lib -c $(BuildConfiguration) -o $(build.binariesdirectory)\nuget'

    - task: DotNetCoreCLI@2
      displayName: Nupkg (Cli)
      inputs:
        command: 'custom'
        custom: 'pack'
        arguments: 'Cli -c $(BuildConfiguration) -o $(build.binariesdirectory)\nuget'

    - task: AntiMalware@3
      inputs:
        InputType: 'Basic'
        ScanType: 'CustomScan'
        FileDirPath: '$(Build.binariesdirectory)'
        EnableServices: true
        SupportLogOnError: false
        TreatSignatureUpdateFailureAs: 'Warning'
        SignatureFreshness: 'UpToDate'
        TreatStaleSignatureAs: 'Warning'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Interim Build Artifacts'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)\nuget'
        ArtifactName: 'NugetBuilds'

    # Signing task requires .NET Core 2.X
    - task: UseDotNet@2
      inputs:
        packageType: 'runtime'
        version: '2.2.x'

    - task: EsrpCodeSigning@1
      inputs:
        ConnectedServiceName: 'CodeSignforATSAN'
        FolderPath: '$(build.binariesdirectory)\nuget'
        Pattern: '*.nupkg'
        signConfigType: 'inlineSignParams'
        inlineOperation: |
          [ 
              {
                  "keyCode": "CP-401405",
                  "operationSetCode": "NuGetSign",
                  "parameters": [ ],
                  "toolName": "sign",
                  "toolVersion": "1.0"
              },
              {
                  "keyCode": "CP-401405",
                  "operationSetCode": "NuGetVerify",
                  "parameters": [ ],
                  "toolName": "sign",
                  "toolVersion": "1.0"
              }
          ]
        SessionTimeout: '60'
        MaxConcurrency: '50'
        MaxRetryAttempts: '5'

    - task: PowerShell@2
      displayName: Compile CodeSign Summaries for Publication
      inputs:
        targetType: 'inline'
        script: |
          mkdir $(build.binariesdirectory)\CodeSign
          Get-ChildItem -Path $(build.binariesdirectory) -Recurse -Filter CodeSign* | foreach { Copy-Item -Path $_.FullName -Destination $(build.binariesdirectory)\CodeSign\$_.Name }

    - task: PublishBuildArtifacts@1
      displayName: 'Publish CodeSign Summaries'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)\CodeSign'
        ArtifactName: 'CodeSign_Nuget'

    - task: PowerShell@2
      displayName: Prepare Artifacts
      inputs:
        targetType: 'inline'
        script: |
          Move-Item -Path "$(build.binariesdirectory)\nuget\*.nupkg" -Destination "$(build.artifactstagingdirectory)"
          Move-Item -Path "$(build.binariesdirectory)\nuget\*.snupkg" -Destination "$(build.artifactstagingdirectory)"

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'BINARIES'

    - task: NuGetCommand@2
      displayName: Deploy Nuget Release
      enabled: true
      inputs:
        command: 'push'
        packagesToPush: '$(build.artifactstagingdirectory)/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'CST-E Nuget CI'
        verbosityPush: 'Normal'

- stage: Hashes
  jobs:
  - job: CombineAndPublish
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download HASH files'
      inputs:
        downloadType: specific
        itemPattern: 'HASHES/*.txt'
        downloadPath: '$(build.binariesdirectory)'

    - powershell: 'Get-Content $(build.binariesdirectory)\HASHES\HASHES_LINUX.txt, $(build.binariesdirectory)\HASHES\HASHES_MAC.txt, $(build.binariesdirectory)\HASHES\HASHES_WINDOWS.txt | Set-Content $(build.binariesdirectory)\HASHES.txt'
      displayName: 'PowerShell Script'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish HASHES'
      inputs:
        PathtoPublish: '$(build.binariesdirectory)/HASHES.txt'
        ArtifactName: 'HASHES'

    - task: GitHubRelease@1
      displayName: 'GitHub release update'
      inputs:
        gitHubConnection: 'Gabe-Asa'
        action: edit
        tag: 'v$(Build.BuildNumber)'
        title: 'v$(Build.BuildNumber)'
        assets: '$(build.binariesdirectory)/HASHES.txt'
        assetUploadMode: replace
        isDraft: false
        isPreRelease: false
        changeLogCompareToRelease: lastNonDraftRelease