name: ASA SDL

trigger: none
pr: none

schedules:
- cron: "0 6 * * *"
  displayName: Daily 2am
  branches:
    include:
    - master
    - releases/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use DotNet 3.1
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- script: 'dotnet tool install -g nbgv'
  displayName: 'Install GitVersioning'
  
- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
    outputFormat: 'sarif'

- task: SdtReport@1
  inputs:
    VstsConsole: false
    TsvFile: false
    AllTools: false
    APIScan: false
    BinSkim: false
    CodesignValidation: false
    CredScan: true
    FortifySCA: false
    FxCop: false
    ModernCop: false
    MSRD: false
    PoliCheck: false
    RoslynAnalyzers: false
    SDLNativeRules: false
    Semmle: true
    SemmleBreakOn: 'Error'
    TSLint: false
    ToolLogsNotFoundAction: 'Standard'

- task: DotNetCoreCLI@2
  displayName: Build Asa
  inputs:
    command: 'build'
    projects: '$(build.sourcesdirectory)\Cli\Cli.csproj'

- task: ComponentGovernanceComponentDetection@0
  displayName: Component Detection
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: notice@0
  displayName: Notice Generator
  inputs:
    outputformat: 'text'

- task: PublishPipelineArtifact@1
  displayName: Publish CredScan Result
  inputs:
    targetPath: '$(Pipeline.Workspace)\_sdt\logs\CredentialScanner\CredentialScanner-matches.sarif'
    artifact: 'CredScan.sarif'

- task: PublishPipelineArtifact@1
  displayName: Publish JS Semmle Result
  inputs:
    targetPath: '$(Pipeline.Workspace)\_sdt\logs\Semmle\javascript\microsoft.AttackSurfaceAnalyzer-javascript-1.sarif'
    artifact: 'SemmleJS.sarif'

- task: PublishPipelineArtifact@1
  displayName: Publish SDT Report
  inputs:
    targetPath: '$(Pipeline.Workspace)\_sdt\logs\SdtReport.html'
    artifact: 'SdtReport.html'