//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttackSurfaceAnalyzerGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttackSurfaceAnalyzerGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Results.
        /// </summary>
        internal static string AnalyzeResults {
            get {
                return ResourceManager.GetString("AnalyzeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Run Id.
        /// </summary>
        internal static string BaseRunId {
            get {
                return ResourceManager.GetString("BaseRunId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status messages appear here after starting analysis..
        /// </summary>
        internal static string BaseStatus {
            get {
                return ResourceManager.GetString("BaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        internal static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Type.
        /// </summary>
        internal static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Collectors.
        /// </summary>
        internal static string ChooseCollectors {
            get {
                return ResourceManager.GetString("ChooseCollectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a monitor run to evaluate..
        /// </summary>
        internal static string ChooseMonitor {
            get {
                return ResourceManager.GetString("ChooseMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect snapshot data about the current state of the system and monitor for changes..
        /// </summary>
        internal static string CollectSnapshotDesc {
            get {
                return ResourceManager.GetString("CollectSnapshotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare a base scan and a product scan to determine changes made to the system..
        /// </summary>
        internal static string CompareDesc {
            get {
                return ResourceManager.GetString("CompareDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Run Id.
        /// </summary>
        internal static string CompareRunId {
            get {
                return ResourceManager.GetString("CompareRunId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing.
        /// </summary>
        internal static string Comparing {
            get {
                return ResourceManager.GetString("Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        internal static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted database..
        /// </summary>
        internal static string DeletedDatabase {
            get {
                return ResourceManager.GetString("DeletedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIsplay Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done writing!.
        /// </summary>
        internal static string DoneWriting {
            get {
                return ResourceManager.GetString("DoneWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating Collect Run Ids.
        /// </summary>
        internal static string EnumeratingCollectRunIds {
            get {
                return ResourceManager.GetString("EnumeratingCollectRunIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating Monitor Run Ids.
        /// </summary>
        internal static string EnumeratingMonitorRunIds {
            get {
                return ResourceManager.GetString("EnumeratingMonitorRunIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error collecting from.
        /// </summary>
        internal static string Err_CollectingFrom {
            get {
                return ResourceManager.GetString("Err_CollectingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine latest run id. Can&apos;t continue..
        /// </summary>
        internal static string Err_CouldntDetermineOneRun {
            get {
                return ResourceManager.GetString("Err_CouldntDetermineOneRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine latest two run ids. Can&apos;t continue..
        /// </summary>
        internal static string Err_CouldntDetermineTwoRun {
            get {
                return ResourceManager.GetString("Err_CouldntDetermineTwoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must collect some results before performing analysis..
        /// </summary>
        internal static string Err_NeedResults {
            get {
                return ResourceManager.GetString("Err_NeedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No collectors have been defined..
        /// </summary>
        internal static string Err_NoCollectors {
            get {
                return ResourceManager.GetString("Err_NoCollectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No monitors have been defined..
        /// </summary>
        internal static string Err_NoMonitors {
            get {
                return ResourceManager.GetString("Err_NoMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That runid was already used. Must use a unique runid for each run. Use --overwrite to discard previous run information..
        /// </summary>
        internal static string Err_RunIdAlreadyUsed {
            get {
                return ResourceManager.GetString("Err_RunIdAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all available result types.
        /// </summary>
        internal static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory For Export.
        /// </summary>
        internal static string ExportDirectory {
            get {
                return ResourceManager.GetString("ExportDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export only the selected result type.
        /// </summary>
        internal static string ExportOnly {
            get {
                return ResourceManager.GetString("ExportOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        internal static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first, pre-installation scan should be run on a clean system without the software under test installed..
        /// </summary>
        internal static string FirstScanDesc {
            get {
                return ResourceManager.GetString("FirstScanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path supplied was invalid..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Monitoring.
        /// </summary>
        internal static string LiveMonitoring {
            get {
                return ResourceManager.GetString("LiveMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will monitor your system for changes as they happen..
        /// </summary>
        internal static string LiveMonitoringDesc {
            get {
                return ResourceManager.GetString("LiveMonitoringDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring, press CTRL+C to stop....
        /// </summary>
        internal static string MonitoringPressC {
            get {
                return ResourceManager.GetString("MonitoringPressC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor started for.
        /// </summary>
        internal static string MonitorStartedFor {
            get {
                return ResourceManager.GetString("MonitorStartedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, please visit our.
        /// </summary>
        internal static string MoreInfo1 {
            get {
                return ResourceManager.GetString("MoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page to review the ASA user guide, documentation and source code..
        /// </summary>
        internal static string MoreInfo2 {
            get {
                return ResourceManager.GetString("MoreInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Name.
        /// </summary>
        internal static string OldName {
            get {
                return ResourceManager.GetString("OldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Path.
        /// </summary>
        internal static string OldPath {
            get {
                return ResourceManager.GetString("OldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        internal static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to scan..
        /// </summary>
        internal static string ReadyToScan {
            get {
                return ResourceManager.GetString("ReadyToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        internal static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare, view, and export Scan and Monitor results..
        /// </summary>
        internal static string ResultsDesc {
            get {
                return ResourceManager.GetString("ResultsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run started..
        /// </summary>
        internal static string RunStarted {
            get {
                return ResourceManager.GetString("RunStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Status.
        /// </summary>
        internal static string RunStatus {
            get {
                return ResourceManager.GetString("RunStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Id.
        /// </summary>
        internal static string ScanId {
            get {
                return ResourceManager.GetString("ScanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Type.
        /// </summary>
        internal static string ScanType {
            get {
                return ResourceManager.GetString("ScanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second, post-installation scan should be run after installing the software onto the system..
        /// </summary>
        internal static string SecondScanDesc {
            get {
                return ResourceManager.GetString("SecondScanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a type of result to view..
        /// </summary>
        internal static string SelectResultType {
            get {
                return ResourceManager.GetString("SelectResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Type.
        /// </summary>
        internal static string StartType {
            get {
                return ResourceManager.GetString("StartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Scan.
        /// </summary>
        internal static string StaticScan {
            get {
                return ResourceManager.GetString("StaticScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will scan your system to gather a snapshot of the chosen parameters.  To determine the changes made by the installation of a specific piece of software the system must be scanned at least twice..
        /// </summary>
        internal static string StaticScanDesc {
            get {
                return ResourceManager.GetString("StaticScanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Location.
        /// </summary>
        internal static string StoreLocation {
            get {
                return ResourceManager.GetString("StoreLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory For Export.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your telemetry opt out setting is now.
        /// </summary>
        internal static string TelemetryOptOut {
            get {
                return ResourceManager.GetString("TelemetryOptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send usage data to Microsoft to help us improve our products..
        /// </summary>
        internal static string UsageData {
            get {
                return ResourceManager.GetString("UsageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Surface Analyzer catalogues the changes made to an operating system attack surface by the installation of new software. ASA can be used to take a snapshot of your system state before and after the installation of product(s) and displays the changes made to a number of key elements of the system attack surface allowing you to see what attack surfaces may be exposed after installation of the target product(s). ASA was developed by Microsoft..
        /// </summary>
        internal static string WelcomeBody {
            get {
                return ResourceManager.GetString("WelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Attack Surface Analyzer.
        /// </summary>
        internal static string WelcomeHeader {
            get {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
    }
}
