// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CST.AttackSurfaceAnalyzer.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttackSurfaceAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType
        {
            get
            {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attack Surface Analyzer is not running as Administrator/Root and cannot run collections..
        /// </summary>
        public static string AdminWarning
        {
            get
            {
                return ResourceManager.GetString("AdminWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyze Results.
        /// </summary>
        public static string AnalyzeResults
        {
            get
            {
                return ResourceManager.GetString("AnalyzeResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This application collects usage data to help us improve Attack Surface Analyzer..
        /// </summary>
        public static string ApplicationHasTelemetry
        {
            get
            {
                return ResourceManager.GetString("ApplicationHasTelemetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For our privacy policy visit: {0}..
        /// </summary>
        public static string ApplicationHasTelemetry2
        {
            get
            {
                return ResourceManager.GetString("ApplicationHasTelemetry2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To disable telemetry run &apos;{0}&apos;..
        /// </summary>
        public static string ApplicationHasTelemetry3
        {
            get
            {
                return ResourceManager.GetString("ApplicationHasTelemetry3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base Run Id.
        /// </summary>
        public static string BaseRunId
        {
            get
            {
                return ResourceManager.GetString("BaseRunId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status messages appear here after starting analysis..
        /// </summary>
        public static string BaseStatus
        {
            get
            {
                return ResourceManager.GetString("BaseStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Begin {0}..
        /// </summary>
        public static string Begin
        {
            get
            {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Certificates
        {
            get
            {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Type.
        /// </summary>
        public static string ChangeType
        {
            get
            {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose Collectors.
        /// </summary>
        public static string ChooseCollectors
        {
            get
            {
                return ResourceManager.GetString("ChooseCollectors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose a monitor run to evaluate..
        /// </summary>
        public static string ChooseMonitor
        {
            get
            {
                return ResourceManager.GetString("ChooseMonitor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collectors.
        /// </summary>
        public static string Collectors
        {
            get
            {
                return ResourceManager.GetString("Collectors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collect snapshot data about the current state of the system and monitor for changes..
        /// </summary>
        public static string CollectSnapshotDesc
        {
            get
            {
                return ResourceManager.GetString("CollectSnapshotDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compare a base scan and a product scan to determine changes made to the system..
        /// </summary>
        public static string CompareDesc
        {
            get
            {
                return ResourceManager.GetString("CompareDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Product Run Id.
        /// </summary>
        public static string CompareRunId
        {
            get
            {
                return ResourceManager.GetString("CompareRunId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comparing {0} vs {1}..
        /// </summary>
        public static string Comparing
        {
            get
            {
                return ResourceManager.GetString("Comparing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed {0} in {1}..
        /// </summary>
        public static string Completed
        {
            get
            {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Contents
        {
            get
            {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created
        {
            get
            {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        public static string CurrentState
        {
            get
            {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted
        {
            get
            {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted database..
        /// </summary>
        public static string DeletedDatabase
        {
            get
            {
                return ResourceManager.GetString("DeletedDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleted database at {0}. 💣.
        /// </summary>
        public static string DeletedDatabaseAt
        {
            get
            {
                return ResourceManager.GetString("DeletedDatabaseAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DIsplay Name.
        /// </summary>
        public static string DisplayName
        {
            get
            {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done writing!.
        /// </summary>
        public static string DoneWriting
        {
            get
            {
                return ResourceManager.GetString("DoneWriting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Due To Filter.
        /// </summary>
        public static string DueToFilter
        {
            get
            {
                return ResourceManager.GetString("DueToFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dumping data from database located at {0}..
        /// </summary>
        public static string DumpingDataFromDatabase
        {
            get
            {
                return ResourceManager.GetString("DumpingDataFromDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End {0}..
        /// </summary>
        public static string End
        {
            get
            {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enumerating Collect Run Ids.
        /// </summary>
        public static string EnumeratingCollectRunIds
        {
            get
            {
                return ResourceManager.GetString("EnumeratingCollectRunIds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enumerating Monitor Run Ids.
        /// </summary>
        public static string EnumeratingMonitorRunIds
        {
            get
            {
                return ResourceManager.GetString("EnumeratingMonitorRunIds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not get file permissions for: {0}.
        /// </summary>
        public static string Err_AccessControl
        {
            get
            {
                return ResourceManager.GetString("Err_AccessControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error collecting from {1}: {2} {3}.
        /// </summary>
        public static string Err_CollectingFrom
        {
            get
            {
                return ResourceManager.GetString("Err_CollectingFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine latest run id. Can&apos;t continue..
        /// </summary>
        public static string Err_CouldntDetermineOneRun
        {
            get
            {
                return ResourceManager.GetString("Err_CouldntDetermineOneRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine latest two run ids. Can&apos;t continue..
        /// </summary>
        public static string Err_CouldntDetermineTwoRun
        {
            get
            {
                return ResourceManager.GetString("Err_CouldntDetermineTwoRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Json error parsing your filters.json file. {0} {1} {2} {3} {4}.
        /// </summary>
        public static string Err_FiltersFile
        {
            get
            {
                return ResourceManager.GetString("Err_FiltersFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not run &apos;ss&apos; do you have &apos;iproute2&apos; installed?.
        /// </summary>
        public static string Err_Iproute2
        {
            get
            {
                return ResourceManager.GetString("Err_Iproute2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not run/parse &apos;lsof&apos;..
        /// </summary>
        public static string Err_Lsof
        {
            get
            {
                return ResourceManager.GetString("Err_Lsof", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must collect some results before performing analysis..
        /// </summary>
        public static string Err_NeedResults
        {
            get
            {
                return ResourceManager.GetString("Err_NeedResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No collectors have been defined..
        /// </summary>
        public static string Err_NoCollectors
        {
            get
            {
                return ResourceManager.GetString("Err_NoCollectors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No monitors have been defined..
        /// </summary>
        public static string Err_NoMonitors
        {
            get
            {
                return ResourceManager.GetString("Err_NoMonitors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provided output path {0} does not exist..
        /// </summary>
        public static string Err_OutputPathNotExist
        {
            get
            {
                return ResourceManager.GetString("Err_OutputPathNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attack Surface Analyzer must be run as Administrator..
        /// </summary>
        public static string Err_RunAsAdmin
        {
            get
            {
                return ResourceManager.GetString("Err_RunAsAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attack Surface Analyzer must be run as root..
        /// </summary>
        public static string Err_RunAsRoot
        {
            get
            {
                return ResourceManager.GetString("Err_RunAsRoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to That runid was already used. Must use a unique runid for each run. Use --overwrite to discard previous run information..
        /// </summary>
        public static string Err_RunIdAlreadyUsed
        {
            get
            {
                return ResourceManager.GetString("Err_RunIdAlreadyUsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excluding Hive.
        /// </summary>
        public static string ExcludingHive
        {
            get
            {
                return ResourceManager.GetString("ExcludingHive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export all available result types.
        /// </summary>
        public static string ExportAll
        {
            get
            {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output Directory For Export.
        /// </summary>
        public static string ExportDirectory
        {
            get
            {
                return ResourceManager.GetString("ExportDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string Exporting
        {
            get
            {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export only the selected result type.
        /// </summary>
        public static string ExportOnly
        {
            get
            {
                return ResourceManager.GetString("ExportOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string ExportOptions
        {
            get
            {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not parse {0} {1} {2} {3} {4}..
        /// </summary>
        public static string FailedParsed
        {
            get
            {
                return ResourceManager.GetString("FailedParsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to delete database at {0}. {1}:{2}.
        /// </summary>
        public static string FailedToDeleteDatabase
        {
            get
            {
                return ResourceManager.GetString("FailedToDeleteDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files
        {
            get
            {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This appears to be the first run with database {0}. There are no runs to list..
        /// </summary>
        public static string FirstRunListRunsError
        {
            get
            {
                return ResourceManager.GetString("FirstRunListRunsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The first, pre-installation scan should be run on a clean system without the software under test installed..
        /// </summary>
        public static string FirstScanDesc
        {
            get
            {
                return ResourceManager.GetString("FirstScanDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Found
        {
            get
            {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} created..
        /// </summary>
        public static string FoundCreated
        {
            get
            {
                return ResourceManager.GetString("FoundCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} deleted..
        /// </summary>
        public static string FoundDeleted
        {
            get
            {
                return ResourceManager.GetString("FoundDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} modified..
        /// </summary>
        public static string FoundModified
        {
            get
            {
                return ResourceManager.GetString("FoundModified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        public static string Hash
        {
            get
            {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path supplied was invalid..
        /// </summary>
        public static string InvalidPath
        {
            get
            {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Live Monitoring.
        /// </summary>
        public static string LiveMonitoring
        {
            get
            {
                return ResourceManager.GetString("LiveMonitoring", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will monitor your system for changes as they happen..
        /// </summary>
        public static string LiveMonitoringDesc
        {
            get
            {
                return ResourceManager.GetString("LiveMonitoringDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loaded Analyses from {0}..
        /// </summary>
        public static string LoadedAnalyses
        {
            get
            {
                return ResourceManager.GetString("LoadedAnalyses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loaded filters: {0}.
        /// </summary>
        public static string LoadedFilters
        {
            get
            {
                return ResourceManager.GetString("LoadedFilters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified
        {
            get
            {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitoring, press CTRL+C to stop....
        /// </summary>
        public static string MonitoringPressC
        {
            get
            {
                return ResourceManager.GetString("MonitoringPressC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitor started for.
        /// </summary>
        public static string MonitorStartedFor
        {
            get
            {
                return ResourceManager.GetString("MonitorStartedFor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For more information, please visit our.
        /// </summary>
        public static string MoreInfo1
        {
            get
            {
                return ResourceManager.GetString("MoreInfo1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to page to review the ASA user guide, documentation and source code..
        /// </summary>
        public static string MoreInfo2
        {
            get
            {
                return ResourceManager.GetString("MoreInfo2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There were no collect runs in the database..
        /// </summary>
        public static string NoCollectRuns
        {
            get
            {
                return ResourceManager.GetString("NoCollectRuns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There were no monitor runs in the database..
        /// </summary>
        public static string NoMonitorRuns
        {
            get
            {
                return ResourceManager.GetString("NoMonitorRuns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Old Name.
        /// </summary>
        public static string OldName
        {
            get
            {
                return ResourceManager.GetString("OldName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Old Path.
        /// </summary>
        public static string OldPath
        {
            get
            {
                return ResourceManager.GetString("OldPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output Directory For Export.
        /// </summary>
        public static string OutputDirectory
        {
            get
            {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output written to: {0}.
        /// </summary>
        public static string OutputWrittenTo
        {
            get
            {
                return ResourceManager.GetString("OutputWrittenTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path
        {
            get
            {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions
        {
            get
            {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        public static string Ports
        {
            get
            {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready to scan..
        /// </summary>
        public static string ReadyToScan
        {
            get
            {
                return ResourceManager.GetString("ReadyToScan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string Registry
        {
            get
            {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compare, view, and export Scan and Monitor results..
        /// </summary>
        public static string ResultsDesc
        {
            get
            {
                return ResourceManager.GetString("ResultsDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run started..
        /// </summary>
        public static string RunStarted
        {
            get
            {
                return ResourceManager.GetString("RunStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run Status.
        /// </summary>
        public static string RunStatus
        {
            get
            {
                return ResourceManager.GetString("RunStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run Id.
        /// </summary>
        public static string ScanId
        {
            get
            {
                return ResourceManager.GetString("ScanId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        public static string Scanning
        {
            get
            {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan Type.
        /// </summary>
        public static string ScanType
        {
            get
            {
                return ResourceManager.GetString("ScanType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The second, post-installation scan should be run after installing the software onto the system..
        /// </summary>
        public static string SecondScanDesc
        {
            get
            {
                return ResourceManager.GetString("SecondScanDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a type of result to view..
        /// </summary>
        public static string SelectResultType
        {
            get
            {
                return ResourceManager.GetString("SelectResultType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ServiceName
        {
            get
            {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services
        {
            get
            {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size
        {
            get
            {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting {0}..
        /// </summary>
        public static string Starting
        {
            get
            {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting {0} {1}..
        /// </summary>
        public static string StartingN
        {
            get
            {
                return ResourceManager.GetString("StartingN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Type.
        /// </summary>
        public static string StartType
        {
            get
            {
                return ResourceManager.GetString("StartType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Static Scan.
        /// </summary>
        public static string StaticScan
        {
            get
            {
                return ResourceManager.GetString("StaticScan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will scan your system to gather a snapshot of the chosen parameters.  To determine the changes made by the installation of a specific piece of software the system must be scanned at least twice..
        /// </summary>
        public static string StaticScanDesc
        {
            get
            {
                return ResourceManager.GetString("StaticScanDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Store Location.
        /// </summary>
        public static string StoreLocation
        {
            get
            {
                return ResourceManager.GetString("StoreLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        public static string StoreName
        {
            get
            {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject
        {
            get
            {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully Parsed {0} {1} {2} {3} {4}..
        /// </summary>
        public static string SuccessParsed
        {
            get
            {
                return ResourceManager.GetString("SuccessParsed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your telemetry opt out setting is now {0}..
        /// </summary>
        public static string TelemetryOptOut
        {
            get
            {
                return ResourceManager.GetString("TelemetryOptOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send usage data to Microsoft to help us improve our products..
        /// </summary>
        public static string UsageData
        {
            get
            {
                return ResourceManager.GetString("UsageData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users
        {
            get
            {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value
        {
            get
            {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attack Surface Analyzer catalogues the changes made to an operating system attack surface by the installation of new software. ASA can be used to take a snapshot of your system state before and after the installation of product(s) and displays the changes made to a number of key elements of the system attack surface allowing you to see what attack surfaces may be exposed after installation of the target product(s). ASA was developed by Microsoft..
        /// </summary>
        public static string WelcomeBody
        {
            get
            {
                return ResourceManager.GetString("WelcomeBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Attack Surface Analyzer.
        /// </summary>
        public static string WelcomeHeader
        {
            get
            {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
    }
}
