//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttackSurfaceAnalyzer.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AttackSurfaceAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        public static string Comparing {
            get {
                return ResourceManager.GetString("Comparing", resourceCulture);
            }
        }
        
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        public static string DeletedDatabase {
            get {
                return ResourceManager.GetString("DeletedDatabase", resourceCulture);
            }
        }
        
        public static string DoneWriting {
            get {
                return ResourceManager.GetString("DoneWriting", resourceCulture);
            }
        }
        
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        public static string EnumeratingCollectRunIds {
            get {
                return ResourceManager.GetString("EnumeratingCollectRunIds", resourceCulture);
            }
        }
        
        public static string EnumeratingMonitorRunIds {
            get {
                return ResourceManager.GetString("EnumeratingMonitorRunIds", resourceCulture);
            }
        }
        
        public static string Err_CollectingFrom {
            get {
                return ResourceManager.GetString("Err_CollectingFrom", resourceCulture);
            }
        }
        
        public static string Err_CouldntDetermineOneRun {
            get {
                return ResourceManager.GetString("Err_CouldntDetermineOneRun", resourceCulture);
            }
        }
        
        public static string Err_CouldntDetermineTwoRun {
            get {
                return ResourceManager.GetString("Err_CouldntDetermineTwoRun", resourceCulture);
            }
        }
        
        public static string Err_NoMonitors {
            get {
                return ResourceManager.GetString("Err_NoMonitors", resourceCulture);
            }
        }
        
        public static string Err_RunIdAlreadyUsed {
            get {
                return ResourceManager.GetString("Err_RunIdAlreadyUsed", resourceCulture);
            }
        }
        
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        public static string MonitoringPressC {
            get {
                return ResourceManager.GetString("MonitoringPressC", resourceCulture);
            }
        }
        
        public static string MonitorStartedFor {
            get {
                return ResourceManager.GetString("MonitorStartedFor", resourceCulture);
            }
        }
        
        public static string TelemetryOptOut {
            get {
                return ResourceManager.GetString("TelemetryOptOut", resourceCulture);
            }
        }
        
        public static string WelcomeHeader {
            get {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
        
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string AnalyzeResults {
            get {
                return ResourceManager.GetString("AnalyzeResults", resourceCulture);
            }
        }
        
        public static string BaseRunId {
            get {
                return ResourceManager.GetString("BaseRunId", resourceCulture);
            }
        }
        
        public static string BaseStatus {
            get {
                return ResourceManager.GetString("BaseStatus", resourceCulture);
            }
        }
        
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        public static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        public static string ChooseCollectors {
            get {
                return ResourceManager.GetString("ChooseCollectors", resourceCulture);
            }
        }
        
        public static string ChooseMonitor {
            get {
                return ResourceManager.GetString("ChooseMonitor", resourceCulture);
            }
        }
        
        public static string CollectSnapshotDesc {
            get {
                return ResourceManager.GetString("CollectSnapshotDesc", resourceCulture);
            }
        }
        
        public static string CompareDesc {
            get {
                return ResourceManager.GetString("CompareDesc", resourceCulture);
            }
        }
        
        public static string CompareRunId {
            get {
                return ResourceManager.GetString("CompareRunId", resourceCulture);
            }
        }
        
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        public static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        public static string Err_NeedResults {
            get {
                return ResourceManager.GetString("Err_NeedResults", resourceCulture);
            }
        }
        
        public static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        public static string ExportDirectory {
            get {
                return ResourceManager.GetString("ExportDirectory", resourceCulture);
            }
        }
        
        public static string ExportOnly {
            get {
                return ResourceManager.GetString("ExportOnly", resourceCulture);
            }
        }
        
        public static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        public static string FirstScanDesc {
            get {
                return ResourceManager.GetString("FirstScanDesc", resourceCulture);
            }
        }
        
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        public static string LiveMonitoring {
            get {
                return ResourceManager.GetString("LiveMonitoring", resourceCulture);
            }
        }
        
        public static string LiveMonitoringDesc {
            get {
                return ResourceManager.GetString("LiveMonitoringDesc", resourceCulture);
            }
        }
        
        public static string MoreInfo1 {
            get {
                return ResourceManager.GetString("MoreInfo1", resourceCulture);
            }
        }
        
        public static string MoreInfo2 {
            get {
                return ResourceManager.GetString("MoreInfo2", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string OldName {
            get {
                return ResourceManager.GetString("OldName", resourceCulture);
            }
        }
        
        public static string OldPath {
            get {
                return ResourceManager.GetString("OldPath", resourceCulture);
            }
        }
        
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        public static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        
        public static string ReadyToScan {
            get {
                return ResourceManager.GetString("ReadyToScan", resourceCulture);
            }
        }
        
        public static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        public static string ResultsDesc {
            get {
                return ResourceManager.GetString("ResultsDesc", resourceCulture);
            }
        }
        
        public static string RunStatus {
            get {
                return ResourceManager.GetString("RunStatus", resourceCulture);
            }
        }
        
        public static string ScanId {
            get {
                return ResourceManager.GetString("ScanId", resourceCulture);
            }
        }
        
        public static string ScanType {
            get {
                return ResourceManager.GetString("ScanType", resourceCulture);
            }
        }
        
        public static string SecondScanDesc {
            get {
                return ResourceManager.GetString("SecondScanDesc", resourceCulture);
            }
        }
        
        public static string SelectResultType {
            get {
                return ResourceManager.GetString("SelectResultType", resourceCulture);
            }
        }
        
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        public static string StartType {
            get {
                return ResourceManager.GetString("StartType", resourceCulture);
            }
        }
        
        public static string StaticScan {
            get {
                return ResourceManager.GetString("StaticScan", resourceCulture);
            }
        }
        
        public static string StaticScanDesc {
            get {
                return ResourceManager.GetString("StaticScanDesc", resourceCulture);
            }
        }
        
        public static string StoreLocation {
            get {
                return ResourceManager.GetString("StoreLocation", resourceCulture);
            }
        }
        
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        public static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string UsageData {
            get {
                return ResourceManager.GetString("UsageData", resourceCulture);
            }
        }
        
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string WelcomeBody {
            get {
                return ResourceManager.GetString("WelcomeBody", resourceCulture);
            }
        }
        
        public static string RunStarted {
            get {
                return ResourceManager.GetString("RunStarted", resourceCulture);
            }
        }
        
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        public static string Err_NoCollectors {
            get {
                return ResourceManager.GetString("Err_NoCollectors", resourceCulture);
            }
        }
        
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        public static string Collectors {
            get {
                return ResourceManager.GetString("Collectors", resourceCulture);
            }
        }
        
        public static string Err_AccessControl {
            get {
                return ResourceManager.GetString("Err_AccessControl", resourceCulture);
            }
        }
        
        public static string Err_FiltersFile {
            get {
                return ResourceManager.GetString("Err_FiltersFile", resourceCulture);
            }
        }
        
        public static string FailedParsed {
            get {
                return ResourceManager.GetString("FailedParsed", resourceCulture);
            }
        }
        
        public static string LoadedFilters {
            get {
                return ResourceManager.GetString("LoadedFilters", resourceCulture);
            }
        }
        
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        public static string SuccessParsed {
            get {
                return ResourceManager.GetString("SuccessParsed", resourceCulture);
            }
        }
        
        public static string DueToFilter {
            get {
                return ResourceManager.GetString("DueToFilter", resourceCulture);
            }
        }
        
        public static string ExcludingHive {
            get {
                return ResourceManager.GetString("ExcludingHive", resourceCulture);
            }
        }
        
        public static string OutputWrittenTo {
            get {
                return ResourceManager.GetString("OutputWrittenTo", resourceCulture);
            }
        }
    }
}
