### YamlMime:ManagedReference
items:
- uid: AttackSurfaceAnalyzer.Utils.ConfigurationReader
  commentId: T:AttackSurfaceAnalyzer.Utils.ConfigurationReader
  id: ConfigurationReader
  parent: AttackSurfaceAnalyzer.Utils
  children:
  - AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile(System.String)
  langs:
  - csharp
  - vb
  name: ConfigurationReader
  nameWithType: ConfigurationReader
  fullName: AttackSurfaceAnalyzer.Utils.ConfigurationReader
  type: Class
  source:
    remote:
      path: Lib/Utils/ConfigurationReader.cs
      branch: gfs/FunctionalTests
      repo: https://github.com/Microsoft/AttackSurfaceAnalyzer.git
    id: ConfigurationReader
    path: ../Lib/Utils/ConfigurationReader.cs
    startLine: 8
  assemblies:
  - AsaLib
  namespace: AttackSurfaceAnalyzer.Utils
  syntax:
    content: 'public class ConfigurationReader : object'
    content.vb: >-
      Public Class ConfigurationReader
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile(System.String)
  commentId: M:AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile(System.String)
  id: LoadConfigurationFromFile(System.String)
  parent: AttackSurfaceAnalyzer.Utils.ConfigurationReader
  langs:
  - csharp
  - vb
  name: LoadConfigurationFromFile(String)
  nameWithType: ConfigurationReader.LoadConfigurationFromFile(String)
  fullName: AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile(System.String)
  type: Method
  source:
    remote:
      path: Lib/Utils/ConfigurationReader.cs
      branch: gfs/FunctionalTests
      repo: https://github.com/Microsoft/AttackSurfaceAnalyzer.git
    id: LoadConfigurationFromFile
    path: ../Lib/Utils/ConfigurationReader.cs
    startLine: 10
  assemblies:
  - AsaLib
  namespace: AttackSurfaceAnalyzer.Utils
  syntax:
    content: public static JObject LoadConfigurationFromFile(string filename = "Configuration.json")
    parameters:
    - id: filename
      type: System.String
    return:
      type: JObject
    content.vb: Public Shared Function LoadConfigurationFromFile(filename As String = "Configuration.json") As JObject
  overload: AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: AttackSurfaceAnalyzer.Utils
  commentId: N:AttackSurfaceAnalyzer.Utils
  name: AttackSurfaceAnalyzer.Utils
  nameWithType: AttackSurfaceAnalyzer.Utils
  fullName: AttackSurfaceAnalyzer.Utils
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile*
  commentId: Overload:AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile
  name: LoadConfigurationFromFile
  nameWithType: ConfigurationReader.LoadConfigurationFromFile
  fullName: AttackSurfaceAnalyzer.Utils.ConfigurationReader.LoadConfigurationFromFile
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: JObject
  commentId: '!:JObject'
  isExternal: true
  name: JObject
  nameWithType: JObject
  fullName: JObject
